version:  '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    container_name: postgres-db
    networks:
      - easy-scan-network
    volumes:
       - postgres:/data/postgres

  dbadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    networks:
      - easy-scan-network
    volumes:
       - pgadmin:/var/lib/pgadmin
    
  api:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_USERNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - 3000:3000
    networks:
      - easy-scan-network
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      
networks: 
  easy-scan-network:
    driver: bridge
volumes:
    postgres:
    pgadmin: