name: manga_easy_originals
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  manga_easy_sdk:
    git: 
      url: https://github.com/lucascardo12/manga_easy_sdk.git
      ref: v1.4.1

dev_dependencies:
  lints: ^2.1.1
