x-logging:
  &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'
version: '3'

services:
  database:
    image: postgres:15.3
    <<: *x-logging
    restart: unless-stopped
    networks:
      - originals
    environment:
      - POSTGRES_DB=${_API_DB_SCHEMA}
      - POSTGRES_USER=${_API_DB_USER}
      - POSTGRES_PASSWORD=${_API_DB_PASS}
    ports:
      - 5432:5432
  api:
    restart: always
    build: api
    <<: *x-logging
    environment:
      DB_DATABASE: ${_API_DB_SCHEMA}
      DB_USER: ${_API_DB_USER}
      DB_PASSWORD: ${_API_DB_PASS}
      DB_PORT: ${_API_DB_PORT}
      JWT_key: ${_API_JWT}
      DB_HOST: ${_API_DB_HOST}
    networks:
      - originals
    ports:
      - 8080:8080
  nginx:
    restart: always
    build: nginx
    <<: *x-logging
    ports:
      - "443:443"
    networks:
      - originals
networks:
  originals:

    # compose up -d --no-build --remove-orphans
    # .\gradlew build -x test
